// generate-pdfs.js — Wrap markdown templates → PDF.
// This is a stub: production rendering requires `puppeteer` or `markdown-pdf` (not yet pinned).
// Reference: ESTV/AFC accepts both paper and electronic submissions; CO art. 958f authorizes
// electronic archival of accounting records under OLICo (RS 221.431).

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { basename, extname, resolve } from 'node:path';

/**
 * Render a markdown file to PDF.
 * @param {string} mdPath
 * @param {string} outPath
 * @returns {Promise<{input:string, output:string, engine:string}>}
 */
export async function renderMarkdownToPDF(mdPath, outPath) {
  const md = readFileSync(mdPath, 'utf8');
  // TODO: replace this stub with `puppeteer` or `markdown-pdf` once dependency is added.
  // For now, emit a placeholder file so the pipeline is testable without binary deps.
  try {
    const mod = await import('puppeteer').catch(() => null);
    if (mod) {
      const html = `<html><body><pre>${md.replace(/[<>&]/g, (c) => ({ '<':'&lt;','>':'&gt;','&':'&amp;' }[c]))}</pre></body></html>`;
      const browser = await mod.launch();
      const page = await browser.newPage();
      await page.setContent(html);
      await page.pdf({ path: outPath, format: 'A4' });
      await browser.close();
      return { input: mdPath, output: outPath, engine: 'puppeteer' };
    }
  } catch {
    /* fall through */
  }
  // Stub: write a minimal PDF-like text marker so callers can detect "rendered".
  const stub = `%PDF-1.4 STUB\n% generated by generate-pdfs.js (no PDF engine installed)\n${md}\n%%EOF\n`;
  writeFileSync(outPath, stub);
  return { input: mdPath, output: outPath, engine: 'stub' };
}

function usage() {
  console.log(`Usage: node scripts/generate-pdfs.js <input.md> [--out <output.pdf>]

Render a markdown template to PDF. Requires 'puppeteer' (optional dep) for real PDF output;
otherwise writes a stub placeholder file so the pipeline remains testable.`);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const argv = process.argv.slice(2);
  if (!argv.length || argv.includes('--help') || argv.includes('-h')) { usage(); process.exit(argv.length ? 0 : 1); }
  const input = resolve(argv[0]);
  if (!existsSync(input)) { console.error(`not found: ${input}`); process.exit(2); }
  const outIdx = argv.indexOf('--out');
  const output = outIdx >= 0 ? argv[outIdx + 1] : input.replace(/\.md$/i, '.pdf') || `${basename(input, extname(input))}.pdf`;
  const result = await renderMarkdownToPDF(input, output);
  console.log(JSON.stringify(result, null, 2));
}
